// Diccionario de códigos de país/región a nombre completo (en inglés)
// Fuente: listado provisto por el usuario

export const COUNTRY_NAMES = {
  "AB": "ARAB SATELLITE COMMUNICATIONS ORGANIZATION",
  "ABS": "ABS Global Ltd",
  "ABW": "Aruba",
  "AC": "ASIASAT CORP",
  "AFG": "Afghanistan",
  "AGO": "REPUBLIC OF ANGOLA",
  "AIA": "Anguilla",
  "ALA": "Åland Islands",
  "ALB": "Albania",
  "ALG": "ALGERIA",
  "AND": "Andorra",
  "ARGN": "ARGENTINA",
  "ARM": "Armenia",
  "ASM": "American Samoa",
  "ASRA": "AUSTRIA",
  "ATF": "French Southern Territories",
  "ATG": "Antigua and Barbuda",
  "AUS": "AUSTRALIA",
  "AZE": "Azerbaijan",
  "AZER": "AZERBAIJAN",
  "BDI": "Burundi",
  "BEL": "BELGIUM",
  "BELA": "BELARUS",
  "BEN": "Benin",
  "BERM": "BERMUDA",
  "BES": "Bonaire, Sint Eustatius and Saba",
  "BFA": "Burkina Faso",
  "BGD": "PEOPLES REPUBLIC OF BANGLADESH",
  "BGR": "REPUBLIC OF BULGARIA",
  "BHR": "Bahrain",
  "BHS": "Bahamas",
  "BIH": "Bosnia and Herzegovina",
  "BLM": "Saint Barthélemy",
  "BLZ": "Belize",
  "BOL": "BOLIVIA",
  "BRAZ": "BRAZIL",
  "BRB": "Barbados",
  "BRN": "Brunei Darussalam",
  "BTN": "Bhutan",
  "BVT": "Bouvet Island",
  "BWA": "Botswana",
  "CA": "CANADA",
  "CAF": "Central African Republic",
  "CCK": "Cocos (Keeling) Islands",
  "CHBZ": "PEOPLES REPUBLIC OF CHINA/BRAZIL",
  "CHL": "Chile",
  "CHLE": "CHILE",
  "CHN": "China",
  "CIS": "COMMONWEALTH OF INDEPENDENT STATES",
  "CIV": "Côte d'Ivoire",
  "CMR": "Cameroon",
  "COD": "Democratic Republic of the Congo",
  "COG": "Congo",
  "COK": "Cook Islands",
  "COL": "COLOMBIA",
  "COM": "Comoros",
  "CPV": "Cabo Verde",
  "CRI": "REPUBLIC OF COSTA RICA",
  "CUB": "Cuba",
  "CUW": "Curaçao",
  "CXR": "Christmas Island",
  "CYM": "Cayman Islands",
  "CYP": "Cyprus",
  "CZCH": "CZECHOSLOVAKIA",
  "CZE": "Czechia",
  "DEN": "DENMARK",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DOM": "Dominican Republic",
  "ECU": "ECUADOR",
  "EGY": "Egypt",
  "EGYP": "EGYPT",
  "ERI": "Eritrea",
  "ESA": "EUROPEAN SPACE AGENCY",
  "ESH": "Western Sahara",
  "ESRO": "EUROPEAN SPACE RESEARCH ORGANIZATION",
  "EST": "ESTONIA",
  "ETH": "FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA",
  "EUME": "EUROPEAN ORGANIZATION FOR THE EXPLOITATION OF METEOROLOGICAL SATELLITES",
  "EUTE": "EUROPEAN TELECOMMUNICATIONS SATELLITE ORGANIZATION (EUTELSAT)",
  "FGER": "FRANCE/GERMANY",
  "FIN": "FINLAND",
  "FJI": "Fiji",
  "FLK": "Falkland Islands (Malvinas)",
  "FR": "FRANCE",
  "FRG": "FEDERAL REPUBLIC OF GERMANY",
  "FRIT": "FRANCE/ITALY",
  "FRO": "Faroe Islands",
  "FRRG": "FRANCE/FEDERAL REPUBLIC OF GERMANY",
  "FSM": "Micronesia (Federated States of)",
  "GAB": "Gabon",
  "GEO": "Georgia",
  "GER": "GERMANY",
  "GGY": "Guernsey",
  "GHA": "REPUBLIC OF GHANA",
  "GIB": "Gibraltar",
  "GIN": "Guinea",
  "GLOB": "GLOBALSTAR",
  "GLP": "Guadeloupe",
  "GMB": "Gambia",
  "GNB": "Guinea-Bissau",
  "GNQ": "Equatorial Guinea",
  "GRD": "Grenada",
  "GREC": "GREECE",
  "GRL": "Greenland",
  "GTM": "Guatemala",
  "GUF": "French Guiana",
  "GUM": "Guam",
  "GUY": "Guyana",
  "HKG": "Hong Kong",
  "HMD": "Heard Island and McDonald Islands",
  "HND": "Honduras",
  "HRV": "Croatia",
  "HTI": "Haiti",
  "HUN": "HUNGARY",
  "IM": "INTERNATIONAL MARITIME SATELLITE ORGANIZATION (INMARSAT)",
  "IMN": "Isle of Man",
  "IND": "INDIA",
  "INDO": "INDONESIA",
  "INMA": "INTERNATIONAL MARITIME SATELLITE ORGANIZATION (INMARSAT)",
  "IOT": "British Indian Ocean Territory",
  "IRAN": "IRAN",
  "IRAQ": "IRAQ",
  "IRID": "IRIDIUM",
  "IRL": "Ireland",
  "IRQ": "Iraq",
  "ISL": "Iceland",
  "ISRA": "ISRAEL",
  "ISRO": "INDIA SPACE RESEARCH ORGANIZATION",
  "ISS": "INTERNATIONAL SPACE STATION",
  "IT": "ITALY",
  "ITSO": "INTERNATIONAL TELECOMMUNICATIONS SATELLITE ORGANIZATION (INTELSAT)",
  "JAM": "Jamaica",
  "JEY": "Jersey",
  "JOR": "HASHEMITE KINGDOM OF JORDAN",
  "JPN": "JAPAN",
  "KAZ": "KAZAKHSTAN",
  "KEN": "REPUBLIC OF KENYA",
  "KGZ": "Kyrgyzstan",
  "KHM": "Cambodia",
  "KIR": "Kiribati",
  "KNA": "Saint Kitts and Nevis",
  "KOR": "KOREA",
  "KWT": "Kuwait",
  "LAOS": "LAOS",
  "LBN": "Lebanon",
  "LBR": "Liberia",
  "LBY": "Libya",
  "LCA": "Saint Lucia",
  "LIE": "Liechtenstein",
  "LKA": "DEMOCRATIC SOCIALIST REPUBLIC OF SRI LANKA",
  "LSO": "Lesotho",
  "LTU": "LITHUANIA",
  "LUXE": "LUXEMBOURG",
  "LVA": "LATVIA",
  "MA": "MOROCCO",
  "MAC": "Macao",
  "MAF": "Saint Martin (French part)",
  "MALA": "MALAYSIA",
  "MCO": "Monaco",
  "MDA": "Moldova, Republic of",
  "MDG": "Madagascar",
  "MDV": "Maldives",
  "MEX": "MEXICO",
  "MHL": "Marshall Islands",
  "MKD": "North Macedonia",
  "MLI": "Mali",
  "MLT": "Malta",
  "MMR": "REPUBLIC OF THE UNION OF MYNAMAR",
  "MNE": "Montenegro",
  "MNG": "MONGOLIA",
  "MNP": "Northern Mariana Islands",
  "MOZ": "Mozambique",
  "MRT": "Mauritania",
  "MSR": "Montserrat",
  "MTQ": "Martinique",
  "MUS": "Mauritius",
  "MWI": "Malawi",
  "MYT": "Mayotte",
  "NAM": "Namibia",
  "NATO": "NORTH ATLANTIC TREATY ORGANIZATION",
  "NCL": "New Caledonia",
  "NER": "Niger",
  "NETH": "NETHERLANDS",
  "NFK": "Norfolk Island",
  "NIC": "Nicaragua",
  "NICO": "NEW ICO",
  "NIG": "NIGERIA",
  "NIU": "Niue",
  "NKOR": "NORTH KOREA",
  "NOR": "NORWAY",
  "NPL": "FEDERAL DEMOCRATIC REPUBLIC OF NEPAL",
  "NRU": "Nauru",
  "NZ": "NEW ZEALAND",
  "O3B": "O3B NETWORKS",
  "OMN": "Oman",
  "ORB": "ORBITAL TELECOMMUNICATIONS SATELLITE (GLOBALSTAR)",
  "PAKI": "PAKISTAN",
  "PAN": "Panama",
  "PCN": "Pitcairn",
  "PER": "PERU",
  "PLW": "Palau",
  "PNG": "Papua New Guinea",
  "POL": "POLAND",
  "POR": "PORTUGAL",
  "PRC": "PEOPLES REPUBLIC OF CHINA",
  "PRES": "PEOPLES REPUBLIC OF CHINA/EUROPEAN SPACE AGENCY",
  "PRI": "Commonwealth of Puerto Rico",
  "PRY": "REPUBLIC OF PARAGUAY",
  "PYF": "French Polynesia",
  "QAT": "STATE OF QATAR",
  "RASC": "REGIONAL AFRICAN SATELLITE COMMUNICATIONS ORG",
  "REU": "Réunion",
  "ROM": "ROMANIA",
  "RP": "REPUBLIC OF PHILIPPINES",
  "RWA": "REPUBLIC OF RWANDA",
  "SAFR": "SOUTH AFRICA",
  "SAUD": "SAUDI ARABIA",
  "SDN": "REPUBLIC OF SUDAN",
  "SEAL": "SEA LAUNCH DEMO",
  "SEN": "Senegal",
  "SES": "SOCIÉTÉ EUROPÉENNE DES SATELLITES",
  "SGS": "South Georgia and the South Sandwich Islands",
  "SHN": "Saint Helena, Ascension and Tristan da Cunha",
  "SING": "SINGAPORE",
  "SJM": "Svalbard and Jan Mayen",
  "SKOR": "SOUTH KOREA",
  "SLB": "Solomon Islands",
  "SLE": "Sierra Leone",
  "SLV": "El Salvador",
  "SMR": "San Marino",
  "SOM": "Somalia",
  "SPM": "Saint Pierre and Miquelon",
  "SPN": "SPAIN",
  "SRB": "Serbia",
  "SSD": "South Sudan",
  "STCT": "SINGAPORE/TAIWAN",
  "STP": "Sao Tome and Principe",
  "SUR": "Suriname",
  "SVK": "Slovakia",
  "SVN": "REPUBLIC OF SLOVENIA",
  "SWED": "SWEDEN",
  "SWTZ": "SWITZERLAND",
  "SWZ": "Eswatini",
  "SXM": "Sint Maarten (Dutch part)",
  "SYC": "Seychelles",
  "SYR": "Syrian Arab Republic",
  "TBD": "TO BE DETERMINED/UNKNOWN",
  "TCA": "Turks and Caicos Islands",
  "TCD": "Chad",
  "TGO": "Togo",
  "THAI": "THAILAND",
  "TJK": "Tajikistan",
  "TKL": "Tokelau",
  "TKM": "TURKMENISTAN",
  "TLS": "Timor-Leste",
  "TMMC": "TURKMENISTAN/MONACO",
  "TON": "Tonga",
  "TTO": "Trinidad and Tobago",
  "TUN": "REPUBLIC OF TUNISIA",
  "TURK": "TURKEY",
  "TUV": "Tuvalu",
  "TWN": "TAIWAN",
  "TZA": "Tanzania, United Republic of",
  "UAE": "UNITED ARAB EMIRATES",
  "UGA": "Uganda",
  "UK": "UNITED KINGDOM",
  "UKR": "UKRAINE",
  "UMI": "United States Minor Outlying Islands",
  "UNKN": "UNKNOWN",
  "URY": "URUGUAY",
  "US": "UNITED STATES OF AMERICA",
  "USBZ": "UNITED STATES/BRAZIL",
  "USSR": "UNION OF SOVIET SOCIALIST REPUBLICS",
  "UZB": "Uzbekistan",
  "VAT": "Holy See",
  "VCT": "Saint Vincent and the Grenadines",
  "VENZ": "VENEZUELA",
  "VGB": "Virgin Islands (British)",
  "VIR": "Virgin Islands (U.S.)",
  "VTNM": "VIETNAM",
  "VUT": "Vanuatu",
  "WLF": "Wallis and Futuna",
  "WSM": "Samoa",
  "YEM": "Yemen",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe"
};
